"""Add image_filename and thumbnail_filename to Slide

Revision ID: c49e91b5e572
Revises: 
Create Date: 2025-08-22 00:06:24.856391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c49e91b5e572'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slide', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('thumbnail_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slide', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_filename')
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
